language: node_js

node_js:
  - '6'

before_script:
  - mysql -e 'create database america_scores;'

script:
  - mysql -u travis america_scores < database/dbcreate.sql
  - ./scripts/travis-mysql.sh
  - npm run eslint -- --failTaskOnError
  - npm run seed
  - npm run test -- --failTaskOnError

services:
  - mysql

after_success:
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha $(find test -name '*.js')

before_deploy:
  - zip -r backend-latest config/ database/ routes/ scripts/ app.js appspec.yml package.json
  - mkdir -p backend
  - mv backend-latest.zip backend/

deploy:
  - provider: s3
    access_key_id: $AMSCORES_AWS_KEY_ID
    secret_access_key: $AMSCORES_AWS_KEY_SECRET
    region: us-east-1
    local_dir: backend
    skip_cleanup: true
    on:
      branch: develop
    bucket: amscores-deploy-dev
  - provider: codedeploy
    access_key_id: $AMSCORES_AWS_KEY_ID
    secret_access_key: $AMSCORES_AWS_KEY_SECRET
    region: us-east-1
    bucket: "amscores-deploy-dev"
    key: backend-latest.zip
    bundle_type: zip
    application: AmScoresBackend
    deployment_group: Development
    on:
      branch: develop
    wait-until-deployed: true
