language: node_js

node_js:
  - '6'

script:
  - npm run eslint -- --failTaskOnError
  - npm run test -- --failTaskOnError

after_success:
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha $(find test -name '*.js')

before_deploy:
  - zip -r latest config/ database/ routes/ scripts/ app.js appspec.yml package.json
  - mkdir -p to_deploy
  - mv latest.zip to_deploy/

deploy:
  - provider: s3
    access_key_id: $AMSCORES_AWS_KEY_ID
    secret_access_key: $AMSCORES_AWS_KEY_SECRET
    region: us-east-1
    local_dir: to_deploy
    skip_cleanup: true
    on:
      branch: develop
    bucket: amscores-deploy-dev
  - provider: codedeploy
    access_key_id: $AMSCORES_AWS_KEY_ID
    secret_access_key: $AMSCORES_AWS_KEY_SECRET
    region: us-east-1
    bucket: "amscores-deploy-dev"
    key: latest.zip
    bundle_type: zip
    application: AmScoresBackend
    deployment_group: Development
    on:
      branch: develop
    wait-until-deployed: true
