language: node_js

node_js:
  - '6'

before_script:
  - mysql -e 'create database america_scores;'

script:
  - mysql -u travis america_scores < database/dbcreate.sql
  - ./scripts/travis-config.sh
  - npm run eslint -- --failTaskOnError
  - npm run seed
  - npm run test -- --failTaskOnError

services:
  - mysql

after_success:
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha $(find test -name '*.js') -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

before_deploy:
  - zip -r backend-latest config/config.js config/connection.js database/ lib/ routes/ scripts/ app.js appspec.yml gulpfile.js package.json
  - mkdir -p backend
  - mv backend-latest.zip backend/

deploy:
  - provider: s3
    access_key_id: $AMSCORES_AWS_KEY_ID
    secret_access_key: $AMSCORES_AWS_KEY_SECRET
    region: us-east-1
    local_dir: backend
    skip_cleanup: true
    upload-dir: prod
    on:
      branch: master
    bucket: amscores-deploy
  - provider: codedeploy
    access_key_id: $AMSCORES_AWS_KEY_ID
    secret_access_key: $AMSCORES_AWS_KEY_SECRET
    region: us-east-1
    bucket: "amscores-deploy"
    key: prod/backend-latest.zip
    bundle_type: zip
    application: AmScoresBackend
    deployment_group: Production
    on:
      branch: master
    wait-until-deployed: true
  - provider: s3
    access_key_id: $AMSCORES_AWS_KEY_ID
    secret_access_key: $AMSCORES_AWS_KEY_SECRET
    region: us-east-1
    local_dir: backend
    skip_cleanup: true
    upload-dir: dev
    on:
      branch: develop
    bucket: amscores-deploy
  - provider: codedeploy
    access_key_id: $AMSCORES_AWS_KEY_ID
    secret_access_key: $AMSCORES_AWS_KEY_SECRET
    region: us-east-1
    bucket: "amscores-deploy"
    key: dev/backend-latest.zip
    bundle_type: zip
    application: AmScoresBackend
    deployment_group: Development
    on:
      branch: develop
    wait-until-deployed: true

notifications:
    slack:
        rooms:
            secure: "twXjUhSJpmRnDrIUnxjGaH7xFHmO0DsVap80MyygjLT3tZAhf+qbWucjMckWDah2YMUUW66tC5CcoGg9NnHfogJx7cZqAKC3QHRlOil/uDyjyqvLEpZn4s/8zhdMKU1HiVO4mhUB00Hwpc62QftGehvZgEo6gNMKRan7Np64vkCvQN//D+fAsSJ9Y2rptKL5mwJwh/XLCnU2i9wcFWrDLHcycGs1M1irg/rba7iRHOXu76IBts2hJg+nzdPRj3GMlqSTOAbMjTFUza4kOrwZeLBT1BJpMOlAjPnFyHp356HJvWNuounu04w4fAtEYt/8dW4cpAlUyRzRVI/8Q+POWIx2c2p1mS5zjQ7pn9yjhdybxoY+OQoj++L6qbpGEpLcDDF3oVSubPP3eBRbBFmaChwnTqEVgXq3NK1UGnZ2ryUk1NbyekLE2+TMJAeRP79zXojlL34MvCt5i1K9d/RiNIkA0zPN1j343DScJ3Vvw2VPsnTkTvKIhDy7wOVvwItWT2SFPDVXkH/k6BgjVSsPWgmpjdapRv3c93Eq5i0s9cPefK7l60J9bQbOjOQu7lOIt7LqzJ0F4IjflpcCcf9Y+HQEud/R000bQK9fDoyPXzRtYniTgyA6sWdwLlB9bmaVdWkhBulUOvRGaFf+lsxq65J1McIaUd+jiREFz3S+MP4="
