language: node_js

node_js:
  - '6'

before_script:
  - mysql -e 'create database america_scores;'

script:
  - mysql -u travis america_scores < database/dbcreate.sql
  - ./scripts/travis-config.sh
  - npm run eslint -- --failTaskOnError
  - npm run seed
  - npm run test -- --failTaskOnError

services:
  - mysql

after_success:
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha $(find test -name '*.js') -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

before_deploy:
  - zip -r backend-latest config/config.js config/connection.js database/ lib/ routes/ scripts/ app.js appspec.yml gulpfile.js package.json
  - mkdir -p backend
  - mv backend-latest.zip backend/

deploy:
  - provider: s3
    access_key_id: $TEMP_AMSCORES_AWS_KEY_ID
    secret_access_key: $TEMP_AMSCORES_AWS_KEY_SECRET
    region: us-east-1
    local_dir: backend
    skip_cleanup: true
    upload-dir: prod
    on:
      branch: kcorring/shift_to_asb_aws
    bucket: asb-aws-deploy
  - provider: codedeploy
    access_key_id: $TEMP_AMSCORES_AWS_KEY_ID
    secret_access_key: $TEMP_AMSCORES_AWS_KEY_SECRET
    region: us-east-1
    bucket: asb-aws-deploy
    key: prod/backend-latest.zip
    bundle_type: zip
    application: ASB-Backend
    deployment_group: Production
    on:
      branch: kcorring/shift_to_asb_aws
    wait-until-deployed: true
  - provider: s3
    access_key_id: $TEMP_AMSCORES_AWS_KEY_ID
    secret_access_key: $TEMP_AMSCORES_AWS_KEY_SECRET
    region: us-east-1
    local_dir: backend
    skip_cleanup: true
    upload-dir: dev
    on:
      branch: develop
    bucket: asb-aws-deploy
  - provider: codedeploy
    access_key_id: $TEMP_AMSCORES_AWS_KEY_ID
    secret_access_key: $TEMP_AMSCORES_AWS_KEY_SECRET
    region: us-east-1
    bucket: asb-aws-deploy
    key: dev/backend-latest.zip
    bundle_type: zip
    application: ASB-Backend
    deployment_group: Development
    on:
      branch: develop
    wait-until-deployed: true

notifications:
    slack:
        on_pull_requests: false
        rooms:
            - secure: "scbo7s/9of6BC/VYd9dmG4lRQRldjWAe9Up6IYC+flKr9MCN5Vh8BoL/LZoDWCP/hkh73uNw4cNwpi5klxzhDpO+F7jXlg8aFiHmluw0acwEWwMLTRmcwLDnh7yYXjg21hk8RTUG76Sp1sWFTpWa/bdr8EPFZmw2c0MQF+57dIWSIQdRxU67uVeJJSQR6DKnmgqeGb1VNNb5fv2vCfZSpL1Kh54440OIBGijWpJiOnXGk4riGiQKm9vaq1CTgb/sEuJkJ8KkiHUOPTZEPBKzEXYhz2V/tyMn6fccpdeTO3iAaMRojeMbOQWUkSL41vRU+99b3/3xiiCFGKNz/ZZEEtnksforXSJAGlYNX0JhHDgBfTkxXvGGzMrQSUX0KYg/Xu+Q3v2mvErDvb4EWgstnPw0YOG6ZujRnWrmmo5widQVWMaOUTiYLV7/7Alxb5lf8gJ6T6bZZgCxXHzvy9+bTSH0dbIdttDPcgcYtG2mDp+8SxWO8g82lbPiCovEG10+8Jxu0EITUFuRJ/DOToa7+Nb8LhGS4IbFM4Dq+bGJQwMtozk1nFX4OQFIb6u2qaVct6Co4pvlW0U9XFAeB3S3a+l+zE5jMyMrl0y/caas3sPAtzSvottXtP3QREt2Ys++W7nSlte16oodFdUd03VgbAlCYEUj5bW3GLf4WhB+Dik=" # dev-ops channel
            - secure: "DjmSNawgrgzUQJvQ2s8UV2+C7Qq5zCdVkYQKVIp5s1FlQgV4/ebGkPxm8R0rNaNErtdcYia9OLCN/5VIyXyNmPDjMubQ/DqKsUe6gsbt9UmrBrOGGEH0/PiVSZIxdCrIuhWfCe4YVmsftp0Fj3a2bkjI3MWD+aW4OKWtUQoMqDWVaokBX8Uq9erq52aQxEgLYyF9LcvZT0TcqLFXEtEH9Z/KQOeQ99gS+8Z61fA77x2pdGFRriO4bRWUoJ/9g323me6EKa1AVtWAOXyoBtqFTgOcG7LTfoELkEQHOOv5SLzJV+wv230z6lSf+v1dgwRUExZ65TG4W6AO5wZs7ly4BUK07yyx+CRhbeVG9ERrvzlpaDU/0xZq1KQjVvi+zkBN2Hjdh3d5a3z1FmUKULQQ7kX13mrsNCiiuOBF5PGa/WdQpGphUYzNCRRzq3qtUrlWN83bo9Z7RePpBypetpCvVTbiTJ/h/sWTEMcYa3sPrLncxXsvGfDFP8pQt5Ytw4hZ1vqznFZDCcyAw1DfQtGjRa+GVOxWwU/hYPpOdvu4fUg2gi80lVSuNg3OSiztgc+GijZWT9bQqTiGcnUr/QkTxi6yW/Fqeyhsr0gqI2MuAcXoY4g3DzGMULPFcdAbsgQF85HJ/ZMv39Xoug3znT6flef8J3VhqfQCq3zR2Ir0VQU=" # backend channel
